### PR TITLE
Feature/refactor proptypes

### PR DESCRIPTION
**Pull request by Ahrengot**
## Upgrades
- Introduce Yarn
- Upgrade React to 15.6.1
- Upgrade React Motion to 0.5.0
- Upgrade Babel to 6.24.1

## Code refactoring
- Use `prop-types` package instead of deprecated `React.PropTypes`
- Refactor code so it's compatible with the latest version of React Motion

### CODE REVIEW

**Comment by Ahrengot** [comment]
Hey @bmcmahen!

I was using this package the other day and React was yelling at me, because this is using React.PropTypes which will be deprecated in React v16. I also went through the code and upgraded everything to work with the latest version of React Motion.

When running the tests, for some reason, the `should emit a reorder event` test sometimes fail (But not always). Is this something you've had to deal with before, or did I screw something up?

**Comment by bmcmahen** [comment]
This is awesome! Thanks. I'm not sure about the `emit reorder event` test, but I'll take a look.

**Comment by Ahrengot** [comment]
Hey @bmcmahen thanks for pulling this in. I see you added a few extra commits on top of this which is great. Is there anything else you need before pushing a new version to NPM so I can pull it into my project?

**Comment by bmcmahen** [comment]
Nope -- I don't think so. And I'm fairly certain I published the new version to NPM. You may need to bump your `package.json` version to 1.2.

**Comment by Ahrengot** [comment]
Ah, my bad! I was looking at the releases here: https://github.com/bmcmahen/react-cast/releases but I see 1.2.1 on NPM now. 

Thanks again!

**Pull request merged**
